In [14]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [15]:
df = pd.read_csv('datasets/loss_function_MSE_RMSE.csv')

In [16]:
df.head()

,id,target,0,1,2,3,4,5,6,7,...,290,291,292,293,294,295,296,297,298,299
0,0,1.0,-1.067,-1.114,-0.616,0.376,1.090,0.467,-0.422,0.460,...,0.220,-0.339,0.254,-0.179,0.352,0.125,0.347,0.436,0.958,-0.824
1,1,0.0,-0.831,0.271,1.716,1.096,1.731,-0.197,1.904,-0.265,...,-0.765,-0.735,-1.158,2.554,0.856,-1.506,0.462,-0.029,-1.932,-0.343
2,2,0.0,0.099,1.390,-0.732,-1.065,0.005,-0.081,-1.450,0.317,...,-1.311,0.799,-1.001,1.544,0.575,-0.309,-0.339,-0.148,-0.646,0.725
3,3,1.0,-0.989,-0.916,-1.343,0.145,0.543,0.636,1.127,0.189,...,-1.370,1.093,0.596,-0.589,-0.649,-0.163,-0.958,-1.081,0.805,3.401
4,4,0.0,0.811,-1.509,0.522,-0.360,-0.220,-0.959,0.334,-0.566,...,-0.178,0.718,-1.017,1.249,-0.596,-0.445,1.751,1.442,-0.393,-0.643

In [17]:
cor = df.corr()
cor = cor.iloc[:,0:5]

In [18]:
cor.head()

              id    target         0         1         2
id      1.000000  0.002565 -0.072283  0.067695  0.010374
target  0.002565  1.000000 -0.085268 -0.111172 -0.036050
0      -0.072283 -0.085268  1.000000  0.039939  0.069846
1       0.067695 -0.111172  0.039939  1.000000  0.023237
2       0.010374 -0.036050  0.069846  0.023237  1.000000

In [20]:
train,test = train_test_split(df,test_size=0.3)
print(train.shape)
print(test.shape)

(175, 302)
(75, 302)

In [23]:
train

,id,target,0,1,2,3,4,5,6,7,...,290,291,292,293,294,295,296,297,298,299
96,96,0.0,-0.825,0.135,-1.307,-0.139,0.728,-1.061,0.459,-0.761,...,0.112,-0.867,1.364,-0.753,-2.351,-1.989,-0.114,-0.744,0.820,0.759
207,207,0.0,-1.484,2.194,0.053,-0.120,-1.347,-1.307,-0.088,0.395,...,-1.153,0.470,0.018,-0.960,-0.935,2.249,-1.264,-0.915,-0.241,1.479
193,193,1.0,-2.292,0.092,0.631,0.128,-0.009,0.137,-0.402,0.166,...,-1.759,1.346,0.960,-0.319,1.685,-0.114,-0.271,-0.276,1.108,1.135
67,67,0.0,0.180,-0.294,0.213,-1.315,1.405,0.736,0.860,0.655,...,-0.631,-2.533,-0.858,0.721,-0.962,-3.013,0.009,1.739,-0.254,-0.529
134,134,0.0,0.097,-0.964,0.160,0.225,0.361,0.461,-0.569,1.168,...,-0.456,0.720,0.905,-1.404,-1.997,0.694,-0.450,-0.509,0.799,1.255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,206,0.0,1.434,-1.713,-0.471,-2.044,1.344,-0.143,0.267,1.089,...,-1.086,-0.341,0.027,0.118,-0.071,0.435,-0.501,-1.161,1.354,1.984
98,98,0.0,-1.602,-0.651,-1.532,1.098,1.439,-0.685,1.854,1.092,...,1.107,-2.225,-0.508,1.720,1.307,-2.732,0.752,1.235,0.168,1.558
105,105,0.0,-0.032,-0.594,-0.111,0.710,0.143,-0.240,-0.669,1.287,...,0.545,0.279,-0.004,1.944,-0.785,2.138,0.594,-0.300,-0.576,0.286
97,97,0.0,0.660,0.126,-1.829,-0.730,-0.683,-0.943,0.892,0.121,...,1.675,-0.182,0.143,0.302,-1.068,0.445,-0.223,1.092,0.816,0.794
202,202,0.0,0.160,0.367,-0.183,0.348,0.254,-0.464,0.299,0.371,...,1.655,-0.342,0.894,-1.995,0.108,-0.158,0.172,-0.163,1.290,0.664

In [22]:
train.iloc[:,120]

96    -0.950
207    0.701
193    0.275
67    -0.827
134   -0.373
       ...
206   -0.144
98     0.053
105   -0.242
97    -0.258
202    0.715
Name: 118, Length: 175, dtype: float64